config/routes.rb
Rails.application.routes.draw do
  get 'organizations/group_organizations_ids', controller: 'group_organizations', action: 'list_organizations'
  get 'locations/group_organization/:group_organization_id', controller: 'group_organizations', action: 'list_locations'
  match 'model_type_prices/:group_organization_id',
        controller: 'group_organizations',
        action: 'calculate_price',
        via: [:get, :post]
  resources :locations
  resources :organizations
  resources :countries
  resources :group_organizations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :group_organization
  has_many :locations
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  include GroupOrganizationsHelper
  include OrganizationsHelper
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:name, :public_name, :organization_type, :pricing_policy, :parent_org_id, :group_organization_id)
    end
end

app/helpers/organizations_helper.rb
require 'nokogiri'
require 'open-uri'

module OrganizationsHelper
  def organization_info(id)
    Organization.find_by_id(id).name if id.present?
  end
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :public_name %>
    <%= form.text_field :public_name %>
  </div>

  <div class="field">
    <%= form.label :organization_type %>
    <%= form.text_field :organization_type %>
    <%#= select_tag :organization_type, options_for_select(%w[Show_room Service Dealer], "Show_room") %>
  </div>

  <div class="field">
    <%= form.label :pricing_policy %>
    <%= form.text_field :pricing_policy %>
    <%#= select_tag :pricing_policy, options_for_select(%w[Flexible Fixed Prestige], "Flexible") %>
  </div>

  <div class="field">
    <%= form.label :parent_org_id %>
    <%= form.text_field :parent_org_id %>
  </div>

  <div class="field">
    <%= form.label :group_organization_id %>
    <%= form.text_field :group_organization_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Public name</th>
      <th>organization_type</th>
      <th>Pricing policy</th>
      <th>Parent org</th>
      <th>Group organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.public_name %></td>
        <td><%= organization.organization_type %></td>
        <td><%= organization.pricing_policy %></td>
        <td><%= organization_info(organization.parent_org_id) %></td>
        <td><%= group_org_name(organization.group_organization_id) %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Public name:</strong>
  <%= @organization.public_name %>
</p>

<p>
  <strong>organization_type:</strong>
  <%= @organization.organization_type %>
</p>

<p>
  <strong>Pricing policy:</strong>
  <%= @organization.pricing_policy %>
</p>

<p>
  <strong>Parent org:</strong>
  <%= @organization.parent_org_id %>
</p>

<p>
  <strong>Group organization:</strong>
  <%= @organization.group_organization_id %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>