config/routes.rb
Rails.application.routes.draw do
  get 'organizations/group_organizations_ids', controller: 'group_organizations', action: 'list_organizations'
  get 'locations/group_organization/:group_organization_id', controller: 'group_organizations', action: 'list_locations'
  match 'model_type_prices/:group_organization_id',
        controller: 'group_organizations',
        action: 'calculate_price',
        via: [:get, :post]
  resources :locations
  resources :organizations
  resources :countries
  resources :group_organizations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group_organization.rb
class GroupOrganization < ApplicationRecord
  belongs_to :country
  has_many :organizations
end

app/controllers/group_organizations_controller.rb
require_relative '../services/calculate_price.rb'
class GroupOrganizationsController < ApplicationController
  before_action :set_group_organization, only: [:show, :edit, :update, :destroy]
  include CountriesHelper
  include GroupOrganizationsHelper
  include OrganizationsHelper

  # GET /group_organizations
  # GET /group_organizations.json
  def index
    @group_organizations = GroupOrganization.all
  end

  # GET /group_organizations/1
  # GET /group_organizations/1.json
  def show
    @country = Country.find_by_id(@group_organization.country_id)
  end

  # GET /group_organizations/new
  def new
    @group_organization = GroupOrganization.new
  end

  # GET /group_organizations/1/edit
  def edit
  end

  # POST /group_organizations
  # POST /group_organizations.json
  def create
    @group_organization = GroupOrganization.new(group_organization_params)

    respond_to do |format|
      if @group_organization.save
        format.html { redirect_to @group_organization, notice: 'Group organization was successfully created.' }
        format.json { render :show, status: :created, location: @group_organization }
      else
        format.html { render :new }
        format.json { render json: @group_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_organizations/1
  # PATCH/PUT /group_organizations/1.json
  def update
    respond_to do |format|
      if @group_organization.update(group_organization_params)
        format.html { redirect_to @group_organization, notice: 'Group organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_organization }
      else
        format.html { render :edit }
        format.json { render json: @group_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def list_organizations
    ids = params[:group_organization_ids].uniq
    @organizations = []
    ids.each do |id|
      @organizations << GroupOrganization.find_by_id(id).organizations
    end
    render template: 'group_organizations/organizations_list'
  end

  def list_locations
    organizations = GroupOrganization.find_by_id(params[:group_organization_id]).organizations
    @locations = []
    organizations.each do |org|
      @locations << org.locations
    end
    render template: 'group_organizations/locations_list'
  end

  def select_model_type
    @group_organization = GroupOrganization.find_by_id(params[:group_organization_id])
    render partial: 'group_organizations/model_type_form'
  end

  def calculate_price
    @price_info = []
    organization_ids = GroupOrganization.find_by_id(params[:group_organization_id]
    ).organizations.where(pricing_policy: params[:model_type]).pluck(:id)
    base_price = params[:base_price].to_i
    @price_info << organization_ids.map {|id| CalculatePrice.call(id,base_price) }
    render template: 'group_organizations/show_prices'
  end

  # DELETE /group_organizations/1
  # DELETE /group_organizations/1.json
  def destroy
    @group_organization.destroy
    respond_to do |format|
      format.html { redirect_to group_organizations_url, notice: 'Group organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_organization
      @group_organization = GroupOrganization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_organization_params
      params.require(:group_organization).permit(:name, :organization_code,
                                                 :country_id, :group_organization_ids,
                                                 :group_organization_id, :model_type, :base_price)
    end
end

app/helpers/group_organizations_helper.rb
module GroupOrganizationsHelper
  def group_org_name(id)
    GroupOrganization.find_by_id(id).name
  end
end

app/views/group_organizations/_form.html.erb
<%= form_with(model: group_organization, local: true) do |form| %>
  <% if group_organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group_organization.errors.count, "error") %> prohibited this group_organization from being saved:</h2>

      <ul>
        <% group_organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :organization_code %>
    <%= form.number_field :organization_code %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.text_field :country_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/group_organizations/_model_type_form.html.erb
<%= form_with(model: @group_organization, local: true) do |form| %>

  <div class="field">
    <%= form.label :model_type %>
    <%= select_tag 'model_type', options_for_select(%w[Flexible Fixed Prestige], "Flexible") %>
  </div>

  <div class="field">
    <%= form.label :base_price %>
    <%= form.number_field :base_price %>
  </div>

<!--  <div class="actions">-->
    <%#= form.button :submit,:class => 'btn btn-md btn-success', :formtarget => "_blank" do %>
<!--      <i class='fa fa fa-plus'></i> submit-->
    <%# end %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/group_organizations/edit.html.erb
<h1>Editing Group Organization</h1>

<%= render 'form', group_organization: @group_organization %>

<%= link_to 'Show', @group_organization %> |
<%= link_to 'Back', group_organizations_path %>

app/views/group_organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Group Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Organization code</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_organizations.each do |group_organization| %>
      <tr>
        <td><%= group_organization.name %></td>
        <td><%= group_organization.organization_code %></td>
        <td><%= country_name(group_organization.country_id) %></td>
        <td><%= link_to 'Show', group_organization %></td>
        <td><%= link_to 'Edit', edit_group_organization_path(group_organization) %></td>
        <td><%= link_to 'Destroy', group_organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group Organization', new_group_organization_path %>

app/views/group_organizations/locations_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
  </tr>
  </thead>

  <tbody>
  <% @locations.flatten.each do |location| %>
    <tr>
      <td><%= location.name %></td>
      <td><%= location.address %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/group_organizations/new.html.erb
<h1>New Group Organization</h1>

<%= render 'form', group_organization: @group_organization %>

<%= link_to 'Back', group_organizations_path %>

app/views/group_organizations/organizations_list.html.erb
<h1>Organizations</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Public name</th>
    <th>organization_type</th>
    <th>Pricing policy</th>
    <th>Parent organization</th>
    <th>Group organization</th>
  </tr>
  </thead>

  <tbody>
  <% @organizations.flatten.each do |org| %>
    <tr>
      <td><%= org.name %></td>
      <td><%= org.public_name %></td>
      <td><%= org.organization_type %></td>
      <td><%= org.pricing_policy %></td>
      <td><%= organization_info(org.parent_org_id) %></td>
      <td><%= group_org_name(org.group_organization_id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/group_organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group_organization.name %>
</p>

<p>
  <strong>Organization code:</strong>
  <%= @group_organization.organization_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= country_name(@group_organization.country_id)%>
</p>

<%= link_to 'Edit', edit_group_organization_path(@group_organization) %> |
<%= link_to 'Back', group_organizations_path %>

app/views/group_organizations/show_prices.html.erb
<p id="notice"><%= notice %></p>

<h1>Model Type Prices</h1>

<%= render 'model_type_form', group_organization: @group_organization %>

<% unless @price_info.flatten.empty? %>
  <table>
    <thead>
    <tr>
      <th>SI.No</th>
      <th>Name</th>
      <th>Price</th>
    </tr>
    </thead>

    <tbody>
    <% @price_info.flatten.each_with_index do |org_price,i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= org_price[:name] %></td>
        <td><%= org_price[:price] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>